version: "3"
services:
  server_1:
    ports:
      - "5000:5000"
    command: npm start
    build: ./server
  server_2:
    ports:
      - "5001:5000"
    command: npm start
    build: ./server2  
  client:
    ports:
      - "3000:3000"
    command: npm start
    build: ./client  