version: "3"
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      - 80:80
      - 443:443
    restart: always  
  server_1:
    ports:
      - "5000:5000"
    command: npm start
    build: ./server
    restart: always  
  server_2:
    ports:
      - "5001:5000"
    command: npm start
    build: ./server2  
    restart: always  
  client:
    ports:
      - "3000:80"
    command: npm start
    build: ./client  
    restart: always  